Alias: $SCT = http://snomed.info/sct
Alias: $UCUM = http://unitsofmeasure.org
Alias: $LOINC = http://loinc.org
Alias: $CLINVAR = http://www.ncbi.nlm.nih.gov/clinvar
Alias: AUTO = http://tiro.health/fhir/CodeSystem/auto-generated

CodeSystem: SCT
Id: SCT
Title: "SNOMED CT"
Description: "SNOMED CT"
* ^url = "http://snomed.info/sct"
* ^content = #not-present

CodeSystem: UCUM
Id: UCUM
Title: "UCUM"
Description: "UCUM"
* ^url = "http://unitsofmeasure.org"
* ^content = #not-present

CodeSystem: AutoGenerated
Id: auto-generated
Title: "Auto Generated Codes"
Description: "Tiro.health Auto Generate Codes in case common standard CodeSystems are insufficïent."
* ^url = "http://tiro.health/fhir/CodeSystem/auto-generated"
* ^content = #not-present

CodeSystem: DictationProvider
Id: dictation-provider
Title: "Dictation Provider"
Description: "Dictation providers supported by the Atticus report renderer"
* ^status = #active
* ^content = #complete
* #corti "Corti" "Corti AI dictation provider"
* #squire "Squire" "Squire Health dictation provider"