Alias: $SCT = http://snomed.info/sct
Alias: $UCUM = http://unitsofmeasure.org
Alias: $LOINC = http://loinc.org
Alias: $CLINVAR = http://www.ncbi.nlm.nih.gov/clinvar
Alias: AUTO = http://fhir.tiro.health/CodeSystem/auto-generated

CodeSystem: SCT
Id: SCT
Title: "SNOMED CT"
Description: "SNOMED CT"
* ^url = "http://snomed.info/sct"
* ^content = #not-present
* ^experimental = false
* ^caseSensitive = true

CodeSystem: UCUM
Id: UCUM
Title: "UCUM"
Description: "UCUM"
* ^url = "http://unitsofmeasure.org"
* ^content = #not-present
* ^experimental = false
* ^caseSensitive = true

CodeSystem: AutoGenerated
Id: auto-generated
Title: "Auto Generated Codes"
Description: "Tiro.health Auto Generate Codes in case common standard CodeSystems are insufficïent."
* ^url = "http://fhir.tiro.health/CodeSystem/auto-generated"
* ^content = #example
* ^experimental = false
* ^caseSensitive = true
* #urn:uuid:030861fb-a73f-499a-9e7e-471d720c25cf "EAU risicogroep"